### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Mastersam07** [Harjacober/FileSigner#6]
Why not use the GitHub release tag to hold the stable versions/release of the application?

- In that way, all releases can be tracked. One could also get an older version of the application as time goes on.

- Besides, seems better than using external services than google drive

**Comment by Harjacober** [comment]
Hmnnn🤔
Tell me more about the Github release tag.
It would be nice to have something like that instead of the Google drive

**Comment by Harjacober** [comment]
Thanks for the suggestion mate.
I have created a release now.
I'm closing this issue now.
